
# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:

name: app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name:  'ls'
      run: |
           ls -l
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm --prefix /app build --if-present
        npm --prefix /app run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.webapp }}
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
